galaxy_info:
  role_name: vector_role  # ← замените дефис на подчёркивание
  author: reqroot_pro
  description: Installs and configures Vector
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: OracleLinux
      versions:
        - "8"
  galaxy_tags:
    - vector
    - logging
    - monitoring