#SPDX-License-Identifier: MIT-0
---
# defaults file for vector-role
---
vector_version: "0.51.1-1"
vector_service_name: "vector"
vector_tmp_path: "/tmp/vector_{{ vector_version }}_{{ vector_arch.stdout }}.deb"
