---
# Требуемые роли для playbook

# ClickHouse — внешняя роль с Ansible Galaxy
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse

# Vector — твоя собственная роль
- src: git@github.com:Reqroot-pro/vector-role.git
  scm: git
  version: "main"
  name: vector

# Lighthouse — твоя собственная роль
- src: git@github.com:Reqroot-pro/lighthouse-role.git
  scm: git
  version: "main"
  name: lighthouse
