#SPDX-License-Identifier: MIT-0
---
# handlers file for lighthouse-role
---
- name: Reload Nginx
  ansible.builtin.systemd:
    name: "{{ nginx_service_name }}"
    state: reloaded

- name: Fix Lighthouse ownership
  ansible.builtin.file:
    path: "{{ lighthouse_dir }}"
    owner: "{{ lighthouse_user }}"
    group: "{{ lighthouse_group }}"
    recurse: true
