---
- name: Install ClickHouse
  hosts: clickhouse_group
  become: true
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector_group
  become: true
  roles:
    - vector

- name: Install LightHouse
  hosts: lighthouse_group
  become: true
  roles:
    - lighthouse
